Repository r-anime/misato, pull requests merged in 2020-12, with the labels that each got.

#79 Basic web management stuff
  bot/commands/whois.js
  bot/index.js
  core/index.js
  web/frontend/router.js
  web/frontend/util.js
  web/frontend/views/Guild.vue
  web/frontend/views/Management.vue
  web/frontend/views/guild/GuildInfo.vue
  web/frontend/views/guild/GuildMemberInfo.vue
  web/frontend/views/guild/GuildMembers.vue
  web/frontend/views/management/Info.vue
  web/index.js
  web/routes/api.js
  web/routes/discordAuth.js
  web/routes/guilds.js
  web/util.js
Labels: enhancement

#80 Frontend UX improvements
  web/frontend/App.vue
  web/frontend/router.js
  web/frontend/store.js
  web/frontend/views/Guild.vue
  web/frontend/views/guild/GuildMemberInfo.vue
  web/routes/guilds.js
  webpack.config.js
Labels: enhancement

#81 Better convert
  bot/commands/misc/convert.js
Labels: enhancement

#69 Added help to commands lacking "module.exports.help" or missing args …
  bot/commands/debug.js
  bot/commands/misc/avatar.js
  bot/commands/misc/convert.js
  bot/commands/misc/pick.js
  bot/commands/misc/roll.js
  bot/commands/moderation/ban.js
  bot/commands/moderation/kick.js
  bot/commands/moderation/note.js
  bot/commands/moderation/unban.js
  bot/commands/moderation/warn.js
  bot/commands/reload.js
  bot/commands/say.js
  bot/commands/unverify.js
  bot/commands/verify.js
  bot/commands/whois.js
Labels: documentation, enhancement

#70 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#85 Help info from commands
  bot/commands/debug.js
  bot/commands/edit.js
  bot/commands/misc/avatar.js
  bot/commands/misc/convert.js
  bot/commands/misc/joke.js
  bot/commands/misc/pick.js
  bot/commands/misc/roll.js
  bot/commands/moderation/ban.js
  bot/commands/moderation/kick.js
  bot/commands/moderation/note.js
  bot/commands/moderation/unban.js
  bot/commands/moderation/warn.js
  bot/commands/ping.js
  bot/commands/reload.js
  bot/commands/reminders/remind.js
  bot/commands/say.js
  bot/commands/unverify.js
  bot/commands/verify.js
  bot/commands/whois.js
  bot/index.js
Labels: code quality, enhancement

#87 Frontend config for verification role
  bot/commands/unverify.js
  bot/events/verification.js
  bot/index.js
  migrations/1608004537390-create-collection-verificationConfiguration.js
  sample.config.js
  web/frontend/views/guild/GuildInfo.vue
  web/routes/api.js
  web/routes/guilds.js
  web/routes/verification.js
  web/util.js
Labels: enhancement

#88 More frontend improvements
  web/frontend/router.js
  web/frontend/views/Guild.vue
  web/frontend/views/guild/Info.vue
  web/frontend/views/guild/MemberInfo.vue
  web/frontend/views/guild/Members.vue
  web/frontend/views/guild/Verification.vue
  web/routes/verification.js
Labels: enhancement

#89 Message filters!!1!1one
  bot/events/messageCreate.js
  common/filters.js
  package.json
  web/frontend/.eslintrc.yml
  web/frontend/components/FilterEditor.vue
  web/frontend/components/FilterEditorContainsText.vue
  web/frontend/components/FilterEditorMatchesRegexp.vue
  web/frontend/components/FilterEditorMultiple.vue
  web/frontend/components/FilterEditorNode.vue
  web/frontend/router.js
  web/frontend/views/Guild.vue
  web/frontend/views/guild/MessageFilter.vue
  web/frontend/views/guild/Verification.vue
  web/routes/api.js
  web/routes/filters.js
  yarn.lock
Labels: enhancement

#90 Misc ux improvements
  web/frontend/App.vue
  web/frontend/components/FilterEditorMultiple.vue
  web/frontend/views/Guild.vue
  web/frontend/views/Home.vue
Labels: enhancement

#91 Fix issue with data loading for multi-selects
  web/frontend/components/FilterEditorMultiple.vue
Labels: bug
