Repository r-anime/misato, pull requests merged in 2021-03, with the labels that each got.

#97 Basic filter command that redirects to the website
  bot/commands/moderation/filter.js
Labels: enhancement

#101 Filter functions in commands
  bot/commands/moderation/filteradd.js
  bot/commands/moderation/filterdel.js
  bot/events/messageCreate.js
Labels: enhancement

#106 Support deleting notes, warnings, kicks from website
  web/frontend/views/guild/MemberInfo.vue
  web/routes/guilds.js
Labels: enhancement

#109 Bump to webpack@5, webpack-cli@4
  package.json
  yarn.lock
Labels: dependencies

#110 Bump webpack plugins to webpack 5 compatible vers
  package.json
  yarn.lock
Labels: bug, dependencies
