Repository r-anime/misato, pull requests merged in 2022-06, with the labels that each got.

#196 add remindme alias for mage
  src/bot/commands/reminders/remind.js
Labels: enhancement

#197 Make bot log when a user stops boosting and when they leave
  src/bot/events/trackBoosters.js
  src/bot/events/trackMembersLeaving.js
Labels: enhancement

#199 Remove booster logging
  src/bot/events/trackBoosters.js
  src/bot/events/trackMembersLeaving.js
Labels: removal

#198 Add config values, Change where server leave logs go
  sample.config.js
  src/bot/events/trackMembersLeaving.js
Labels: enhancement

#202 Limit whois output to 2000 characters
  src/bot/commands/whois.js
Labels: bug

#205 Build Typescript as part of CI workflow
  .github/workflows/ci.yml
  .gitignore
  package.json
Labels: meta

#204 Server join logging
  src/bot/events/verification.js
Labels: enhancement

#203 Update sample.config and update .whois to include ban length
  sample.config.js
  src/bot/commands/whois.js
Labels: bug, enhancement

#206 use <@!id> for join message mentions
  src/bot/events/messageCreate.js
  src/bot/events/trackMembersLeaving.js
  src/bot/events/verification.js
Labels: enhancement

#208 Fix tags not appearing correctly on logs and whois
  src/bot/commands/whois.js
  src/bot/events/trackMembersLeaving.js
  src/bot/events/verification.js
Labels: bug

#209 Remove ping from whois
  src/bot/commands/whois.js
Labels: bug, fuck

#211 Use .nvmrc to automatically manage prod Node version
  .github/workflows/deploy.yml
  .nvmrc
Labels: devops

#212 Always use latest node for CI runs; update actions
  .github/workflows/ci.yml
Labels: devops

#215 Convert Discord formatting utils to Typescript
  .eslintrc.cjs
  package-lock.json
  package.json
  src/bot/util/discord.ts
Labels: code quality

#213 Ping command improvements
  src/bot/commands/ping.js
Labels: enhancement
